version: '3.7'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      - PORT=8080
  db:
    build: ./postgres_db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}